name: Update playlist.m3u8

on:
  schedule:
    - cron: "0 */6 * * *"  # Esegui ogni 6 ore

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Extract M3U8 link
        id: extract_link
        run: |
          LINK=$(yt-dlp -g https://www.youtube.com/watch?v=2Xn1Bb697A0)
          echo "NEW_LINK=$LINK" >> $GITHUB_ENV

      - name: Update playlist.m3u8
        run: |
          sed -i.bak "/^https:\/\/manifest\.googlevideo\.com\//c\\$NEW_LINK" playlist.m3u8

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u8
          git commit -m "Updated playlist.m3u8 with new M3U8 link"
          git push
        env:
          NEW_LINK: ${{ env.NEW_LINK }}
