name: Update M3U8 Link

on:
  workflow_dispatch: # Esegui manualmente questo workflow

jobs:
  update-m3u8-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Estrai il link M3U8 usando yt-dlp
        run: |
          # Estrai il nuovo link usando yt-dlp con i cookies salvati
          LINK=$(yt-dlp --cookies scripts/cookies.txt -g https://www.youtube.com/watch?v=2Xn1Bb697A0)
          echo "NEW_LINK=$LINK" >> $GITHUB_ENV

      - name: Sostituisci il vecchio link nel file playlist.m3u8
        run: |
          # Sostituisci il vecchio link con il nuovo
          sed -i 's|https://manifest.googlevideo.com/api/manifest/hls_variant/expire/[0-9]*/ei/[a-zA-Z0-9_-]*/id/[a-zA-Z0-9_-]*/source/yt_live_broadcast/requiressl/yes/xpc/[a-zA-Z0-9%=_-]*/tx/[0-9%_,]*|$NEW_LINK|' playlist.m3u8

      - name: Commit e push della modifica
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add playlist.m3u8
          git commit -m "Aggiorna il link M3U8"
          git push

