name: Update m3u8

on:
  schedule:
    - cron: '0 */5 * * *'  # Esegui ogni 5 ore
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Get new M3U8 URL
        id: get-m3u8-url
        run: |
          cat << EOF > script.py
          import requests

          def grab(url):
              response = requests.get(url, timeout=15).text
              if '.m3u8' not in response:
                  print('URL M3U8 non trovato')
                  return None

              end = response.find('.m3u8') + 5
              tuner = 100
              while True:
                  if 'https://' in response[end-tuner : end]:
                      link = response[end-tuner : end]
                      start = link.find('https://')
                      end = link.find('.m3u8') + 5
                      return link[start : end]
                  else:
                      tuner += 5

          video_url = 'https://www.youtube.com/watch?v=2Xn1Bb697A0'
          m3u8_url = grab(video_url)
          print(m3u8_url)
          EOF

          m3u8_url=$(python script.py)
          echo "::set-output name=url::$m3u8_url"

      - name: Update playlist.m3u8 file
        run: |
          m3u8_url=${{ steps.get-m3u8-url.outputs.url }}
          sed -i "s|^https://manifest.googlevideo.com.*|$m3u8_url|" playlist.m3u8

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u8
          git commit -m "TV Lourdes link updated! 🆕"
          git push
