name: Estrai M3U8 link e aggiorna playlist

on:
  workflow_dispatch:

jobs:
  extract-link:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Installazione di yt-dlp
    - name: Installa yt-dlp
      run: |
        sudo apt update
        sudo apt install python3-pip
        pip3 install -U yt-dlp

    # Estrazione del link M3U8 con yt-dlp
    - name: Estrai M3U8 link
      id: extract_link
      run: |
        LINK=$(yt-dlp --cookies scripts/cookies.txt -g https://www.youtube.com/watch?v=2Xn1Bb697A0)
        echo "NEW_LINK=$LINK" >> $GITHUB_ENV

    # Sostituzione del vecchio link nel file playlist.m3u8
    - name: Sostituisci il vecchio link nel file playlist.m3u8
      run: |
        # Sostituisci il vecchio link con il nuovo
        sed -i 's|https://manifest.googlevideo.com/|$NEW_LINK|' playlist.m3u8

    # Commit e push delle modifiche
    - name: Commit e push delle modifiche
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add playlist.m3u8
        git commit -m "Aggiorna link M3U8"
        git push
