name: Update Playlist with M3U8 link

on:
  schedule:
    - cron: "0 */6 * * *"  # Esegui ogni 6 ore
  workflow_dispatch:  # Permette di avviare manualmente il workflow dal sito GitHub

permissions:
  contents: write  # Permesso per scrivere nei contenuti della repository

jobs:
  extract_link:
    runs-on: ubuntu-latest

    steps:
    # Checkout della tua repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Installa yt-dlp
    - name: Install yt-dlp
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install yt-dlp

    # Estrai il link M3U8 con yt-dlp utilizzando il file cookies.txt
    - name: Extract M3U8 link
      id: extract_link
      run: |
        LINK=$(yt-dlp --cookies scripts/cookies.txt -g https://www.youtube.com/watch?v=2Xn1Bb697A0)
        echo "NEW_LINK=$LINK" >> $GITHUB_ENV

    # Modifica il file playlist.m3u8 e committa la modifica
    - name: Update playlist.m3u8
      run: |
        # Sostituisci la vecchia riga con il nuovo link estratto
        sed -i "s|https://manifest.googlevideo.com|$NEW_LINK|g" playlist.m3u8
        
        # Aggiungi e committa il cambiamento
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add playlist.m3u8
        git commit -m "Update playlist.m3u8 with new M3U8 link"
        git push origin main
