name: Update Playlist

on:
  schedule:
    - cron: '0 0 * * *' # Esecuzione giornaliera a mezzanotte UTC
  workflow_dispatch: # Esecuzione manuale

permissions:
  contents: write
  
jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurazione di Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Installazione di Streamlink
      - name: Install Streamlink
        run: sudo apt-get update && sudo apt-get install -y streamlink

      # Esecuzione dello script Python
      - name: Run update script
        run: |
          python3 update_m3u8.py > updated_link.txt
        env:
          XML_FILE: youtubelinks.xml

      # Sostituzione del link nel file playlist.m3u8
      - name: Replace link in playlist
        run: |
          LINK=$(cat updated_link.txt)
          sed -i "s|https://manifest.googlevideo.com.*|$LINK|" playlist.m3u8

      # Committa e push delle modifiche
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u8
          git commit -m "Update playlist.m3u8 with latest stream URL"
          git push
