name: Estrai link M3U8 da YouTube

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract_m3u8_link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp

      - name: Estrai il link M3U8
        run: |
          # Usa i cookies dal file scripts/cookies.txt
          LINK=$(yt-dlp --cookies scripts/cookies.txt -g https://www.youtube.com/watch?v=2Xn1Bb697A0)
          echo "NEW_LINK=$LINK" >> $GITHUB_ENV

      - name: Sostituisci il link nella playlist.m3u8
        run: |
          sed -i 's|https://manifest.googlevideo.com/.*|$NEW_LINK|' playlist.m3u8
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Aggiornato il link M3U8"
          git push
